### ISSUE TITLE
make: tailwindcss: No such file or directory

### ISSUE THREAD

**Issue by johanguse** [sikozonpc/fullstack-go-htmx#1]
Hey, hello!

I need a little help running the project. I ran `make build`  and got this error:

```
tailwindcss -i public/css/styles.css -o public/styles.css
make: tailwindcss: No such file or directory
make: *** [Makefile:2: build] Error 127
```
`go version go1.22.2 linux/amd64`

Also, you need to update the import to a new repository name.

Thanks!

**Comment by sikozonpc** [comment]
Hey @johanguse, thanks for spotting it!

That issue is related to not having the tailwindcss CLI installed. I've updated the docs link with an updated reference to install it without NodeJS.

Also updated the path of the styles which was wrong.
